### ISSUE TITLE
找不到路径

### ISSUE THREAD

**Issue by 1262706090** [3026187875/Vscode-51-#1]
![屏幕截图_20230117_171150](https://user-images.githubusercontent.com/117173536/212856840-0b6d29d0-0478-44db-ba02-5b5e68c81063.png)
无论是在obj还是src都不行

**Comment by leioukupo** [comment]
你按照readme里说的修改了路径嘛？看输出，hex文件生成了，是成功了

**Comment by 1262706090** [comment]
两处都修改了

**Comment by leioukupo** [comment]
> 两处都修改了
不应该呀，你的hex文件都生成了呀。你试一试新建一个文件夹，在文件夹里创建一个c文件，在用快捷键编译试一试

**Comment by 1262706090** [comment]
行，我明天试试

**Comment by 1262706090** [comment]
还是不行，不是路径问题
**************************************************************************************
路径正确
Keil Compiler batch by leioukupo
Compiler path is D:\LenovoQMDownload\SoftMgr\Keil_v5\C51\BIN

C51 COMPILER V9.60.7.0 - SN: K1DZC-VZISWC
COPYRIGHT Copyright (C) 2012 - 2022 ARM Limited or its Affiliates. All rights reserved.

C51 COMPILATION COMPLETE.  0 WARNING(S),  0 ERROR(S)
"move over"
 1.OBJ
系统找不到指定的路径。
系统找不到指定的路径。
找不到 C:\Users\12627\Downloads\Vscode-51-main\build\1
找不到文件
Compiled successfully: build\1.hex
 *  终端将被任务重用，按任意键关闭。 
***************************************************************************************
路径错误
Keil Compiler batch by leioukupo
Compiler path is D:\LenovoQMDownload\SoftMgr\Keil_v5C51\BIN
系统找不到指定的路径。
找不到文件
找不到文件
"move over"
找不到文件
~0,-1
系统找不到指定的路径。
系统找不到指定的路径。
找不到 C:\Users\12627\Downloads\Vscode-51-main\build\1
找不到文件
找不到文件
找不到文件
Compiled successfully: build\1.hex
 *  终端将被任务重用，按任意键关闭。

**Comment by leioukupo** [comment]
那我不清楚了，我clone我的仓库，修改两个bat脚本的keil路径，可以正常编译，没有错误

**Comment by leioukupo** [comment]
> 

你再把hex.bat的keil路径也修改下，忘记了，新版改成了两部分，需要修改三个地方的路径

**Comment by 1262706090** [comment]
好了，没问题。
